### ISSUE TITLE
No Horses

### ISSUE THREAD

**Issue by FanciestBoi** [Sharkgamedev/DurusTheGame#1]
Add horses to the game

**Comment by Shark-Bug-Reporter** [comment]
> 

no

**Comment by Sharkgamedev** [comment]
As of the [intial commit](https://github.com/Sharkgamedev/DurusTheGame/commit/70d775705b583b4a5a6a0d44ecafb5c1b69edf3d) horses have been added.

**Comment by FanciestBoi** [comment]
Still an issue. No horses found in current campaign levels

**Comment by FanciestBoi** [comment]
Please reopen
