### ISSUE TITLE
Collisions glitch

### ISSUE THREAD

**Issue by kyhoggardd** [Sharkgamedev/DurusTheGame#46]
when tabbing out of Durus and tabbing back in, sometimes enemies will get stuck to walls and repeatedly glitch in place

**Comment by Sharkgamedev** [comment]
This is not a collision related issue, I suspect the game lags when alt-tabbing and deltatime shots up causing the obstacle to overshoot it's target and then it's Vector to it's next goal points to the goal right next to it causing it to become infinitely stuck in place,
