### ISSUE TITLE
Enemy in the center of the screen

### ISSUE THREAD

**Issue by kyhoggardd** [Sharkgamedev/DurusTheGame#9]
Fix the singular enemy stuck in the middle of the screen haunting my dreams...

**Comment by Sharkgamedev** [comment]
Provided this problem does not occur in New Levels created by the editor, shows up when the level is loaded, exists in the level file (likely) and does not occur in 'Spiral' it's likely a misplace by the level creator and does not have anything to do with a problem or bug in DURUS.

They will be removed when object editing goes in.
